#ifndef DONKEY_KONG_1981_SPRITES_HH
#define DONKEY_KONG_1981_SPRITES_HH

#include <allegro5/allegro.h>
#include <array>
#include "../core/math.hh"

enum sprite_sheet_id
{
  SSID_JUMP_MAN,
  SSID_WORLD,
  SSID_KONG,
  SSID_TITLE,
  SSID_COUNT,
};

enum sprite_id
{
  SID_MARIO_IDLE,
  SID_MARIO_RUN_0,
  SID_MARIO_RUN_1,
  SID_MARIO_CLIMB_OFF_0,
  SID_MARIO_CLIMB_OFF_1,
  SID_MARIO_CLIMB_OFF_2,
  SID_MARIO_CLIMB_IDLE,
  SID_MARIO_CLIMBING,
  SID_MARIO_JUMPING,
  SID_MARIO_HIT,
  SID_MARIO_DYING_0,
  SID_MARIO_DYING_1,
  SID_MARIO_DYING_2,
  SID_MARIO_IDLE_RED_HAMMER_UP,
  SID_MARIO_IDLE_RED_HAMMER_DOWN,
  SID_MARIO_RUN_0_RED_HAMMER_UP,
  SID_MARIO_RUN_0_RED_HAMMER_DOWN,
  SID_MARIO_RUN_1_RED_HAMMER_UP,
  SID_MARIO_RUN_1_RED_HAMMER_DOWN,
  SID_MARIO_IDLE_YELLOW_HAMMER_UP,
  SID_MARIO_IDLE_YELLOW_HAMMER_DOWN,
  SID_MARIO_RUN_0_YELLOW_HAMMER_UP,
  SID_MARIO_RUN_0_YELLOW_HAMMER_DOWN,
  SID_MARIO_RUN_1_YELLOW_HAMMER_UP,
  SID_MARIO_RUN_1_YELLOW_HAMMER_DOWN,
  SID_LUIGI_IDLE,
  SID_LUIGI_RUN_0,
  SID_LUIGI_RUN_1,
  SID_LUIGI_CLIMB_OFF_0,
  SID_LUIGI_CLIMB_OFF_1,
  SID_LUIGI_CLIMB_OFF_2,
  SID_LUIGI_CLIMB_IDLE,
  SID_LUIGI_CLIMBING,
  SID_LUIGI_JUMPING,
  SID_LUIGI_HIT,
  SID_LUIGI_DYING_0,
  SID_LUIGI_DYING_1,
  SID_LUIGI_DYING_2,
  SID_LUIGI_IDLE_RED_HAMMER_UP,
  SID_LUIGI_IDLE_RED_HAMMER_DOWN,
  SID_LUIGI_RUN_0_RED_HAMMER_UP,
  SID_LUIGI_RUN_0_RED_HAMMER_DOWN,
  SID_LUIGI_RUN_1_RED_HAMMER_UP,
  SID_LUIGI_RUN_1_RED_HAMMER_DOWN,
  SID_LUIGI_IDLE_YELLOW_HAMMER_UP,
  SID_LUIGI_IDLE_YELLOW_HAMMER_DOWN,
  SID_LUIGI_RUN_0_YELLOW_HAMMER_UP,
  SID_LUIGI_RUN_0_YELLOW_HAMMER_DOWN,
  SID_LUIGI_RUN_1_YELLOW_HAMMER_UP,
  SID_LUIGI_RUN_1_YELLOW_HAMMER_DOWN,
  SID_GIRDER_RED,
  SID_GIRDER_ORANGE,
  SID_GIRDER_BLUE,
  SID_LADDER_CYAN,
  SID_LADDER_YELLOW,
  SID_LADDER_WHITE,
  SID_COMMON_BARREL_0,
  SID_COMMON_BARREL_1,
  SID_COMMON_BARREL_2,
  SID_COMMON_BARREL_3,
  SID_COMMON_BARREL_WILD_0,
  SID_COMMON_BARREL_WILD_1,
  SID_BLUE_BARREL_0,
  SID_BLUE_BARREL_1,
  SID_BLUE_BARREL_2,
  SID_BLUE_BARREL_3,
  SID_BLUE_BARREL_WILD_0,
  SID_BLUE_BARREL_WILD_1,
  SID_HOT_FLAME_0,
  SID_HOT_FLAME_1,
  SID_COLD_FLAME_0,
  SID_COLD_FLAME_1,
  SID_OIL_CAN,
  SID_RIVET,
  SID_BARREL_STACK,
  SID_RED_FIREBALL_0,
  SID_RED_FIREBALL_1,
  SID_BLUE_FIREBALL_0,
  SID_BLUE_FIREBALL_1,
  SID_RED_FIREFOX_0,
  SID_RED_FIREFOX_1,
  SID_BLUE_FIREFOX_0,
  SID_BLUE_FIREFOX_1,
  SID_SPRING_CLOSED,
  SID_SPRING_OPEN,
  SID_HAMMER_PICKUP,
  SID_PARASOL_PICKUP,
  SID_HAT_PICKUP,
  SID_BAG_PICKUP,
  SID_CONVEYOR_ORANGE,
  SID_CONVEYOR_ORANGE_CAP_FLAT,
  SID_CONVEYOR_ORANGE_CAP_DIAG_LEFT,
  SID_CONVEYOR_ORANGE_CAP_DIAG_RIGHT,
  SID_WIRE_FENCE,
  SID_HAMMER_BLOW_TINY,
  SID_HAMMER_BLOW_SMALL,
  SID_HAMMER_BLOW_BIG,
  SID_HAMMER_BLOW_POP,
  SID_HEART_FULL,
  SID_HEART_BROKEN,
  SID_MARIO_LIFE,
  SID_LUIGI_LIFE,
  SID_WIDE_LADDER_WHITE,
  SID_WIDE_LADDER_YELLOW,
  SID_WIDE_LADDER_CYAN,
  SID_CEMENT_TUB,
  SID_PINK_BONUS,
  SID_BLUE_BONUS,
  SID_ORANGE_BONUS,
  SID_RED_POLE,
  SID_CYAN_POLE,
  SID_ELEVATOR_BOX,
  SID_KONG_FROWNY,
  SID_KONG_BEAT_CHEST,
  SID_KONG_SMILEY,
  SID_KONG_WITH_BARREL,
  SID_KONG_ROLLING,
  SID_KONG_CLIMB,
  SID_KONG_CLIMB_PAULINE_0,
  SID_KONG_CLIMB_PAULINE_1,
  SID_KONG_STUN_0,
  SID_KONG_STUN_1,
  SID_KONG_STUN_2,
  SID_ORANGUTAN,
  SID_PAULINE_IDLE,
  SID_PAULINE_WIGGLE,
  SID_PAULINE_RESCUED,
  SID_PAULINE_ARSE,
  SID_HELP_CYAN,
  SID_HELP_BLUE,
  SID_HELP_WHITE,
  SID_HELP_FLIPPED_CYAN,
  SID_HELP_FLIPPED_BLUE,
  SID_HELP_FLIPPED_WHITE,
  SID_SCORE_100,
  SID_SCORE_200,
  SID_SCORE_300,
  SID_SCORE_500,
  SID_SCORE_800,
  SID_BLUE_TITLE_DONKEY,
  SID_BLUE_TITLE_KONG,
  SID_RED_TITLE_DONKEY,
  SID_RED_TITLE_KONG,
  SID_CYAN_COPY,
  SID_GOLD_COPY,
  SID_BLACK_BOX,
  SID_RUB,
  SID_END,
  SID_COUNT,
};

struct sprite
{
  sprite_sheet_id ssid;
  rect clip;
  vector2f offset;
};

using sprite_sheet = ALLEGRO_BITMAP*;

/** Called during init to load all sprite sheets. */
bool load_sprite_sheets();

/** Called during shutdown to free sprite sheet memory. */
void unload_sprite_sheets();

/** Provides access to all data needed to blit a sprite. */
std::pair<const sprite&, sprite_sheet> get_sprite_data(sprite_id sid);

/** convenience functions to draw a sprite to the render target. */
void draw_sprite(sprite_id sid, vector2f position_px, bool flip_x = false, bool flip_y = false);
void draw_sprite(sprite_id sid, vector2i position_px, bool flip_x = false, bool flip_y = false);
void draw_centered_sprite(sprite_id sid, vector2f center_position_px, bool flip_x = false, bool flip_y = false);

#endif //DONKEY_KONG_1981_SPRITES_HH
